### ISSUE TITLE
USB ports issue and Thinkpad Media keys

### ISSUE THREAD

**Issue by jackhu9527** [seven-of-eleven/Lenovo-ThinkPad-L13-Yoga-Hackintosh#1]
First of all thanks for your awesome work, I've been able to turn my L13 Yoga into a solid Hackintosh with most of the hardware working properly, which I thought was impossible until a while ago. Big thumb up!

The only really issue that I have for now, is with the USB ports on both sides. While I can use most of my USB adapters, USB card readers without any noticeable issue, the Toshiba Displaylink USB Dock doesn't seem to work when it is connected via the built-in USB ports. The only workaround is to firstly connect a USB-C adapter to the laptop, and then plug the USB dock to the USB 3.0 port built-in the USB-C adapter. The displaylink manager app for mac has been installed previously and was running in the background all the time.

The USB Dock was working flawlessly when I was using the EFI files provided here: [https://github.com/hagenest/thinkpad-l13-yoga-hackintosh ](https://github.com/hagenest/thinkpad-l13-yoga-hackintosh )While with these EFI files many of the hardware didn't work by then, such as the camera and battery manager, the USB dock was working well.

Please feel free to let me know what could be wrong and I hope it can be fixed somehow. 

Lastly it'd be great if you can figure out how to use [Thinkpad Assistant](https://github.com/MSzturc/ThinkpadAssistant) on this L13 Yoga model,  currently people are using it on multiple older Thinkpad models like X1C Gen 7, etc.

No hurry here, please take your time and have a nice day.:)

Thanks,

**Comment by seven-of-eleven** [comment]
I don't have the Display link USB Doc to test but it's likely related to one of these things:

1. I didn't map the ports correctly
2. An additional SSDT is required
3. A change in BIOS settings?
4. Device Properties

I'll explain in more detail below:
**1)** Ports mapped incorrectly - When I mapped my ports all I had was a USB-c adapter and a mouse. I think I mapped them correctly but I may have missed something or I simply didn't add it.  I know when mapping that there were additional "ports" showing that didn't seem to map to anything. (They showed up in the program but didn't activate at all when pluggin/unplugging devices).  I disabled those in my mapping.  I took a look at the hagenest's repo and it has both USBMap.kext and USBInjectAll.kext which may conflict with each other (USBInjectAll should be removed after port mapping is done according to the guide). Additionally the USBMap.kext has the port mapping quite differently from mine. The easy way to test this would be to place USBInjectAll.kext into the Kext folder (remember to remove or disable my USBMap.kext and also change the config.plist `XhciPortlimit` value to **True**). If this enables the Displaylink USB Dock then you know that my mapping missed something. Remember to take a snapshot in Propertree after making changes to your EFI folder to ensure the files are injected.

**2)** An additional SSDT is required - I typically don't add SSDT files unless I know the purpose. When I originally found hagenest's repo I noted that he has quite a few SSDT and Kext files.  I didn't know what they all did so I only added according to the OpenCore guide and then went searching for others as I found the need (battery patch...).  You can test the SSDTs individually or simply add them all to your ACPI folder and see if that fixes the Displaylink USB Dock. Remember to take a snapshot in Propertree after making changes to your EFI folder to ensure the files are injected.

**3)** A change in BIOS setting - I'm not sure if you made any changes in USB BIOS settings when using my EFI? It's possible my UEFI settings need to be adjusted.

**4)** Device Properties - The Device Properties hagenest has are much more extensive that what I've included I'm my EFI config.plist file. Again, when setting up my config.plist file I took the minimalist approach and only included what I needed. I didn't test any external displays/adapters. You could test this by simply coping his Device Property into your config.plist to see if it works.

I'd love to help more but I don't have the Displaylink USB Dock to test with. Please let me know how you make out. Not for me so much but for anyone else that may stop by looking for a solution.

If you need any other help let me know. I'll help when/where I can.

**Comment by seven-of-eleven** [comment]
I forgot to mention regarding ThinkPad Assistant. I have used it in the past on another laptop. I noted most people seem to be moving to YogaSMC. I'm not 100% sure why. You can remove YogaSMC if you like and add install ThinkPad Assistant. I may add that to the Read.me if I find some time over the next week. As a minimum you should install the [YogaSMC preference pane and app](https://github.com/zhen-zen/YogaSMC/releases/tag/1.4.3) to control keys and power management. You need to add the app to you `Login Items` in System Preferences>Users and Groups.
