### ISSUE TITLE
Bluetooth problem

### ISSUE THREAD

**Issue by hieuddo** [seven-of-eleven/Lenovo-ThinkPad-L13-Yoga-Hackintosh#10]
Hi, I have problem with bluetooth.
I can turn on bluetooth, connect to my airpods, but cannot connect to any other bluetooth devices (e.g., logitech and xiaomi mouse).
I also tried to re-map USB and delete unnecessary ports.
Does anyone has the same problem?
Thanks

**Comment by DAlexis74** [comment]
I have tried to use M720 TRIATHLON, could not install, but it works perfectly with HP BT Slim mouse.
I laso tried Sony BT headset, wich works.
I use MacOS from pen drive (Transcent 512GB 420/400 MB/S USB Type C) whic is fast enough.
Also upgraded to 11.4
SD Card Reader RTL522A works with 9-10MB/S.
I have only one camera integrated.
I have I7 10510U  model.
I have a Smart Card reader, which I did not try yet.

**Comment by hieuddo** [comment]
> I have tried to use M720 TRIATHLON, could not install, but it works perfectly with HP BT Slim mouse.
> I laso tried Sony BT headset, wich works.
> I use MacOS from pen drive (Transcent 512GB 420/400 MB/S USB Type C) whic is fast enough.
> Also upgraded to 11.4
> SD Card Reader RTL522A works with 9-10MB/S.
> I have only one camera integrated.
> I have I7 10510U model.
> I have a Smart Card reader, which I did not try yet.

yeap, it's quite weird. I can connect successfully to airrpods, my macbook, logitech keyboard, but the two mice (logi and xiaomi). Don't know if the problem lays on compatibility with mice.

**Comment by seven-of-eleven** [comment]
Hi @hieuddo that is strange.  I haven't tried connecting that many bluetooth devices to my L13.  The most I've tried is my AirPods which worked well. It could be a bluetooth driver issue. You could try a new (or older) kext that may work better. I won't have time to test it over the next week. If you have time and some success please keep us posted here. Thanks.
