### ISSUE TITLE
Incorrect base frequency

### ISSUE THREAD

**Issue by hieuddo** [seven-of-eleven/Lenovo-ThinkPad-L13-Yoga-Hackintosh#12]
As I notice in your specs, your processor is i5-10210U, with base freq 1.6, while the screenshot shows it is 2.11GHz.

I have the same issue. My cpu is i7-10510U that has base freq of 1.8GHz and max freq 4.9GHz. The system reads my cpu as 2.3GHz base (shown in the screenshot)

![image](https://user-images.githubusercontent.com/26546698/143769041-7a6cab27-8118-4b7c-a5eb-62032f108779.png)

So I wanna ask whether it is just for show, or the system reads cpu specs incorrectly, or it is in the config files like .aml files? Does that actually affect cpu performance (running at higher base freq)?

P/s: I use Intel Power Gadget and the maximum frequency that cpu can reach is 4.8.

Thanks for the repo and constantly updates!

**Comment by seven-of-eleven** [comment]
AFAIK the information provided in the "Overview" is purely cosmetic.  I've seen reference to [tutorials](https://www.reddit.com/r/hackintosh/comments/jhrhd4/customisemodify_about_this_mac/) that describe how to change the information to whatever you'd like. So I don't think you need to worry about it.  You're free to change it if you like. Thanks.
