### ISSUE TITLE
Monterey Installation Failure 

### ISSUE THREAD

**Issue by sharome** [seven-of-eleven/Lenovo-ThinkPad-L13-Yoga-Hackintosh#13]
I'm using the latest version of the repo, but after initial install (USB). I restart after it finishes back into the usb to boot into the installed partition, then the Apple Logo will show for about 3-4 seconds and then it shuts off and reboots. I will say that what I'm trying is a bit unorthodox, but I am dual booting with Windows 11. The drive is GUID Partition Table though so it should be fine, and the TPM chip and Secure Boot are both off. 

Any help would be appreciated. Thanks

**Comment by seven-of-eleven** [comment]
I'm not that familiar with dual booting as I've never used it myself. One thing that could be causing an issue is the ssdt_data.aml in the ACPI folder. This is used for power management. The OpenCore [guide notes this can cause data injection issues](https://dortania.github.io/OpenCore-Post-Install/universal/pm.html#cleaning-up). I'm not sure what the impact of that would be but try remove it and disable CPUFriend.kext (be sure to update your config.plist to reflect the changes). Hopefully that resolves the issue for you.

**Comment by sharome** [comment]
> I'm not that familiar with dual booting as I've never used it myself. One thing that could be causing an issue is the ssdt_data.aml in the ACPI folder. This is used for power management. The OpenCore [guide notes this can cause data injection issues](https://dortania.github.io/OpenCore-Post-Install/universal/pm.html#cleaning-up). I'm not sure what the impact of that would be but try remove it and disable CPUFriend.kext (be sure to update your config.plist to reflect the changes). Hopefully that resolves the issue for you.

Thanks, I'll try that today. But on a completely unrelated note, should the SMBIOS in the config.plist be empty? If I understood your instructions correct it should be filled out Post Install.

Thanks

**Comment by seven-of-eleven** [comment]
AFAIK the SMBIOS can be created at any time but the default config has default values in it. Do not try and log into Apple services without updating the values.

The OpenCore guide has the SMBIOS created prior to install so that may be the best approach. I created my config.plist and simply removed the values prior to updating my repo to prevent issues. Best of luck.

**Comment by sharome** [comment]
> > I'm not that familiar with dual booting as I've never used it myself. One thing that could be causing an issue is the ssdt_data.aml in the ACPI folder. This is used for power management. The OpenCore [guide notes this can cause data injection issues](https://dortania.github.io/OpenCore-Post-Install/universal/pm.html#cleaning-up). I'm not sure what the impact of that would be but try remove it and disable CPUFriend.kext (be sure to update your config.plist to reflect the changes). Hopefully that resolves the issue for you.
> 
> Thanks, I'll try that today. But on a completely unrelated note, should the SMBIOS in the config.plist be empty? If I understood your instructions correct it should be filled out Post Install.
> 
> Thanks

Well I've tried this and it still isn't booting. Has the same problem, should I reinstall with the new EFI? Because I'm trying to boot into the installed partition.

**Comment by sharome** [comment]
Okay I did a new installation to the partition and it still not booting. How can I enable verbose boot on OpenCore, can it help?

**Comment by seven-of-eleven** [comment]
Verbose boot can be enabled by adding "-v" to the boot-args of the config.plist file.

**Comment by sharome** [comment]
Okay thanks, I will let you know what happens.

**Comment by sharome** [comment]
Hi, I tried to add to the boot-args but when I save it erases my entry, should it go here?
<img width="991" alt="Screen Shot 2022-03-02 at 11 27 09 am" src="https://user-images.githubusercontent.com/77049616/156271524-6a4cae57-0df6-4063-a099-f63c9d2ec45e.png">
If not where should I add the boot argument. Thanks

Also how should I add it? Should I add a space or an underscore between the other argument.

**Comment by seven-of-eleven** [comment]
I typically use ProperTree to edit my config.plist file but any plist editor should work fine. You want to add it to the `Value` not the `Key`. So the Value would be `-v rtsx_sleep_wake_delay_ms=1000`
Make sure there is a space b/w -v and the rtsx...

**Comment by sharome** [comment]
Thanks I'll try that
