### ISSUE TITLE
Intel optane...???

### ISSUE THREAD

**Issue by FidelGB** [seven-of-eleven/Lenovo-ThinkPad-L13-Yoga-Hackintosh#14]
Hi, I have a Thinkpad L13 with the same hardware that the Hardware section in readme file except the storage. My laptop has 512 GB ssd + 32 gb optane, i'm actually linux user and never, but never I used optane storage and I know that these is incompatible with hackintosh (boot show kernel panic), so when I disable nvme in config.plist file, it gains access to the installation but I can't install because nvme was disable in config file... So... Is there any way to disable only intel optane storage in config file?

Pd. Sorry for my bad english :s

Greetings from Mexico 🇲🇽

**Comment by seven-of-eleven** [comment]
I'm not familiar with disabling Intel optane. It is possible to disable or prevent it from mounting. I know within MacOS you can [prevent drives from being mounted](https://discussions.apple.com/docs/DOC-7942) or similar [instruction here](https://www.reddit.com/r/hackintosh/comments/gygkvy/how_to_prevent_windows_linux_or_any_drive_from/). There is likely a way to restrict it with Opencore. Check out [this on TonyMac](https://www.tonymacx86.com/threads/intel-optane.229309/page-2). They seem to have had some success.

If you just want to test install MacOS, you can install it on an attached USB drive. Then if you enjoy it you can reinstall it onto the internal drive.

Best of luck

**Comment by FidelGB** [comment]
Good idea! today I'll try to do these, so, if it works, I want update your readme file with instructions to users with same computer with Intel Optane :D

**Comment by FidelGB** [comment]
I can't use with Intel Optane memory. I purchased a unit without optane and it works. I have a month using hackintosh with your EFI folder and works perfectly. So I made a Pull Request (#16 ) to Readme file specifying that units with intel optane do not work. Thank you so much!

Greetings from Mexico 🇲🇽
