### ISSUE TITLE
Did you mange to solve issue "Scrolling using trackpad while hovering link will opening that link in browser"?

### ISSUE THREAD

**Issue by igavrysh** [seven-of-eleven/Lenovo-ThinkPad-L13-Yoga-Hackintosh#15]
Hi,

Thx for sharing EFI folder here!

I have Lenovo Thinkpad X1 Yoga Gen 3.

I tried many repos for my laptop, however the issue of auto click while scrolling with middle button + trackpoint persists.

e.g. whenever I scroll using Trackpoint - pointing finger on Trackpoint and thumb on middle button - every link, clickable image etc which falls under mouse pointer automatically opens (if I am using a browser).

Do you experience the same issue with your build? Did you mange to fix it?

**Comment by seven-of-eleven** [comment]
Hi I don't experience that issue. The middle button opens a link in a new tab on my laptop. Sorry I can't be of more help. Best of luck.
