### ISSUE TITLE
Fix link in section "CPUFriend power management"

### ISSUE THREAD

**Issue by legymhueck** [seven-of-eleven/Lenovo-ThinkPad-L13-Yoga-Hackintosh#18]
Could you please fix the link:
Yours is "https://github.com/fewtarius/CPUFriendFriend" -> leads to error 404

Is it this one?: https://github.com/acidanthera/CPUFriend

Thanks for maintaining this repo!

**Comment by seven-of-eleven** [comment]
Link has been fixed. Thanks for letting me know it was broken.
