### ISSUE TITLE
Please revert VoodooI2C 2.7 to 2.6.5 in latest release

### ISSUE THREAD

**Issue by alexjaixd** [seven-of-eleven/Lenovo-ThinkPad-L13-Yoga-Hackintosh#19]
Hi, in your latest 0.8.2 release, you've updated Voodooi2c from 2.6.5 to 2.7. This version of Voodooi2c (specifically Voodooi2cHID bundled) causes the Wacom AES pen to not function at all, only finger touch works. This issue has already been reported to Voodooi2c official repository by others (https://github.com/VoodooI2C/VoodooI2C/issues/500). However there's currently no fix for it yet. My own Thinkpad Yoga 260, 370 and L13 Yoga all had this problem and has been fixed by reverting back to Voodooi2c 2.6.5.

**Comment by seven-of-eleven** [comment]
@alexjaixd Thanks for the heads up on this. I rarely use the pen input and wouldn't have noticed this for some time. I'll revert the kext later this week and update OpenCore at the same time.

**Comment by alexjaixd** [comment]
No problems. Thanks for maintaining this repo, will report any problems if found.

**Comment by Mifaxav** [comment]
Hey, i did this on the latest efi but its ruining my sleep

Hence on version 2.7.0 with broken pen input. 

It seems Zhen-zen has gotten a method to fix it. Any way I can compile his VoodooI2CHID kext myself or any way I could contact him?

**Comment by seven-of-eleven** [comment]
Hi. @NotMifa has mentioned he has an update that will fix it. Should be pushing an update soon.
