### ISSUE TITLE
Experiencing freezing when installing Catalina

### ISSUE THREAD

**Issue by sektor1952** [seven-of-eleven/Lenovo-ThinkPad-L13-Yoga-Hackintosh#2]
I want to thank you for putting this together, everything seems to be working great except I haven't been able to do a full install yet as it freezes in the middle of an install.

I know you referenced an issue with the nvme drive that came with yours, it wasn't the samsung drive?  Because mine has a Samsung MZVLB256HBHQ drive and yes I did add the nvme fix kext that was listed in the open core guide, could it be there is a slight variant in the hardware that I need to tweak somethings?

**Comment by seven-of-eleven** [comment]
Hi sektor1952, my ThinkPad came with the Samsung drive.  I replaced it with the WD drive as I'd read to many mixed reviews  with issues using the NVME fix kext, similar to what you have described. As an alternate if you have an extra USB or external hard drive lying around you could try and install onto that to see if it is the Samsung drive that is causing the issue. I didn't install Catalina so it could also be an issue specific to it as well. One final thing I noted with BigSur was that I needed a network connection during the install (I think it was a result of how I built my installer USB but you can test that as well). All the best.

**Comment by sektor1952** [comment]
I replaced the drive as well and it's been working fine ever since.  I had planned on getting a terrabyte drive anyway.
