### ISSUE TITLE
Built-in SmartCard Reader

### ISSUE THREAD

**Issue by alexjaixd** [seven-of-eleven/Lenovo-ThinkPad-L13-Yoga-Hackintosh#20]
Not an issue. Just want to report the built-in smart card reader(Alcor AU9540) works out of the box after a usb remap to enable the HS06 port, using the native Mac OS smart card driver.  So if your computer has this option, it can be used for authentication purposes or even logging in using a smart card paired with your local account. 

Official documentation from Apple itself: https://support.apple.com/en-hk/guide/deployment/depc705651a9/web
![Screenshot 2022-09-18 at 3 53 16 AM](https://user-images.githubusercontent.com/86264021/190874303-9815987f-07ca-44c3-a888-a9448c7995fc.png)
![Screenshot 2022-09-18 at 3 54 20 AM](https://user-images.githubusercontent.com/86264021/190874315-cd9c2b3e-b262-4992-866e-604b2c8b526b.png)
![Screenshot 2022-09-18 at 4 01 35 AM](https://user-images.githubusercontent.com/86264021/190874518-e129974a-7b32-4329-a389-035cdad0242b.png)
![Screenshot 2022-09-18 at 3 54 00 AM](https://user-images.githubusercontent.com/86264021/190874307-f70c2f40-af24-42d4-9ea9-8d16803255ef.png)

**Comment by seven-of-eleven** [comment]
That's great news. Just to clarify you created a new USB map and removed the Sinetek-rtsx.kext? If you don't mind sharing the new USB mapping and I'll include it in the next EFI update. (Will save me from remapping.)

Thanks

**Comment by alexjaixd** [comment]
@seven-of-eleven I haven't removed Sinetek-rtsx.kext nor delete the "rtsx_sleep_wake_delay_ms=1000" boot-args, that's to do with the SD card reader, unless there's anything I should worry about conflicting between the SD card reader and the Smart Card reader?
Here's the USB mapping for the smart card reader.
Keep in mind for machines without smart card reader, HS06 will just be left blank.
[USBMap.kext.zip](https://github.com/seven-of-eleven/Lenovo-ThinkPad-L13-Yoga-Hackintosh/files/9637809/USBMap.kext.zip)

**Comment by seven-of-eleven** [comment]
My bad. I thought you were referring to the SD card reader. It makes much more sense to me now.  

**Thank you**. I'll include it in the next release (coming next month with new OC version).
