### ISSUE TITLE
ACPI compatibility with Yoga-520-15ikb (Digitizer)

### ISSUE THREAD

**Issue by JerryI** [seven-of-eleven/Lenovo-ThinkPad-L13-Yoga-Hackintosh#22]
Hi there,
this is not an issue. I found out in therms of the hardware it looks quite simmilar to Yoga-520-15ikb model.
I have a great success with my own similar approach, but wacom active pen (or digitizer or stylus) is still not working. 
I've seen you managed to get it work. That's great!

Could you pls, give me a hint, which one of ACPI files does correspond to the fixes related to the pen support?
I am using the same Kexts (not sure about the version). Or like, did you have some issues when you were setting it up?
In IORegistry I can find something I2C1@15,1 which has WCOM field attached to VoodooI2CControllerDriver

Thanks

**Comment by FidelGB** [comment]
Hi there,

you can check this comment in another opened issue, that's works for me

https://github.com/seven-of-eleven/Lenovo-ThinkPad-L13-Yoga-Hackintosh/issues/17#issuecomment-1301652023

**Comment by seven-of-eleven** [comment]
@JerryI the pen is only working with VoodooI2C 2.6.5. Any newer version and the pen won't work. However if you're using Ventura you need to upgrade VoodooI2C, otherwise your computer won't shutdown properly #19

**Comment by JerryI** [comment]
> @JerryI the pen is only working with VoodooI2C 2.6.5. Any newer version and the pen won't work. However if you're using Ventura you need to upgrade VoodooI2C, otherwise your computer won't shutdown properly #19

Thanks, @seven-of-eleven I will check it soon!

**Comment by JerryI** [comment]
> @JerryI the pen is only working with VoodooI2C 2.6.5. Any newer version and the pen won't work. However if you're using Ventura you need to upgrade VoodooI2C, otherwise your computer won't shutdown properly #19

It works! I just have replaced VoodooI2C on my Montrey. Amazing! Ive been struggling with that problem since 2021
