### ISSUE TITLE
No wifi on recovery screen

### ISSUE THREAD

**Issue by txanzz** [seven-of-eleven/Lenovo-ThinkPad-L13-Yoga-Hackintosh#24]
Hi, I booted the usb and got to the recovery screen, but there’s not WIFI to download macos. Help!!!

**Comment by seven-of-eleven** [comment]
What version of MacOS are you booting into / trying to install?

**Comment by txanzz** [comment]
Ventura

**Comment by seven-of-eleven** [comment]
Ok, that's strange. Ventura should work without issue.  I plan to update the EFI when OC-0.9.6 comes out if you want to wait till then. Otherwise, you'll need to install the debug files and provide a log file for troubleshooting.
