### ISSUE TITLE
Any possibility of macOS Sonoma support?

### ISSUE THREAD

**Issue by jackhu9527** [seven-of-eleven/Lenovo-ThinkPad-L13-Yoga-Hackintosh#25]
Hi there,

The current release works fine with macOS Monterey, and I really appreciate it. A few weeks ago I managed to find an engineer who helped upgrade the soldered RAM of my L13 Yoga from 8GB to 16GB, which makes this machine a much more usable laptop for my work and study.

However, I realized more apps start to drop support for macOS Monterey and shift their focus to Ventura and the newer Sonoma.

I know one should NOT have expectations when it comes to the OS upgrade of a Hackintosh, after all people may have more important things in their life and they are never paid for their contribution. That said, I would really appreciate it if you could let me know if there is any remote possibility in the near future that you will release an update with Sonoma support. 

Lastly, I wish you a very Merry Christmas and Happy New Year.

Kind regards,
Hu

**Comment by seven-of-eleven** [comment]
I will be updating the EFI over the next week and will include Sonoma support. Not sure if the Pen support will make the transition. It has been limited to an older kext, that may have to be updated. I'll see where that lands. The touch screen should still work.

Merry Christmas to you as well.
