### ISSUE TITLE
(NOT AN ISSUE) Fixed many things...

### ISSUE THREAD

**Issue by NotMifa** [seven-of-eleven/Lenovo-ThinkPad-L13-Yoga-Hackintosh#28]
Just got my laptop a week ago and have fixed a couple minor issues.

These include:

Trackpad and button smoothness
Micro SD card slot
Wacom pen with proper sleep wake

(This is all on macos sonoma)

Any way I could share the efi?
Hopefully become a contributor? 🤞

**Comment by seven-of-eleven** [comment]
@NotMifa That's great to hear. Happy to have someone else contribute. I'm not a Github pro but I'll get you added sometime tomorrow.

**Comment by NotMifa** [comment]
Hey, just accepted the invitation, thanks once again..! Btw, what is the best (fastest) way I could contact you? Maybe talk about a new release, etc, etc

**Comment by seven-of-eleven** [comment]
Sounds like you have an EFI update pretty much ready to go. Update the README with details of the changes and push it, or submit a pull request if you prefer. If you check the Releases you should be able to determine how they are labelled. 

I guess you could create a new branch as well and push it to that, then I can test and merge it. I’m fine either way, just appreciate the help.

You can reach via email - seven.of.eleven@icloud.com
