### ISSUE TITLE
[NOT AN ISSUE - JUST ADVICE + a unrelated question] Memory Card Slot

### ISSUE THREAD

**Issue by xtreme1690** [seven-of-eleven/Lenovo-ThinkPad-L13-Yoga-Hackintosh#29]
Hello hello!

Just wanted to say thank you for this repo! Got my L13 Yoga (with your exact specs!) working nicely on Monterey! (I like using the touch stylus/pen!) Just wanted to suggest that you add a note regarding the memory card slot! You mention in your UEFI settings that you have it disabled, but also mention it under 'Whats Working' - I thought initially that disabling it in UEFI may have some internal MacOS driver work better - But i found i had to re-enable it in UEFI to get it working in MacOS at all. Might just be worth adding a note to let users decide?

---

Also as an unrelated note/question to the above , could you recommend any CPUFriend settings (using CPUFriendFriend.command) to have the system run for performance, rather than power saving like you have? I have admittedly already tried but the ssdt-data.aml that was generated when i tried changing things but this has resulted in kernel panics. (I have also generated a SMBios as per your advice, so still the same MacBookPro model as you used.) Any advice/info here would be appreciated :)

**Comment by NotMifa** [comment]
Hey there, really sorry fir not updating the memory card section of readme. will do them right now. for cpufriend though, i can give you some advice in a while, was On  my way to bed.. Will keep this issue open until then. Thanks for the feedback..!

**Comment by xtreme1690** [comment]
Hey! Just thought i'd poke in and ask if you had any advice on the cpufriend stuff? No worries if you've been busy :)

**Comment by NotMifa** [comment]
hey, really sorry for not following up.. I dont have my L13Y in front of me right now but accordinng to your processor, check out the lowest frequency it can handle which would be required. Furthermore, in the power bias settings, ensure that you have tuned your cpu to a lower point, not lowest(becomes unbareably slow). Also enable the power optimisation settings in the end. after generaation, replace the cpudataprovider kext in files and reboot. try booting using an external USB first

**Comment by xtreme1690** [comment]
Excellent, got it working as best i could! Thanks for your help :D I see there's been an update to the EFI files and there is a newer OC version! Is there any benefit to updating? Really i'd love to update MacOS if we can keep the pen stylus working, but happy to stay on Monterey for the moment if thats the best we can get when it comes to keeping pen usage (As i've kept the older Voodoo kexts because of that) (I know off topic a bit but hey may help someone else!)

**Comment by NotMifa** [comment]
the latest efi supports sonoma with all features working..!

**Comment by xtreme1690** [comment]
Excellent, thanks. Having an issue though with Sonoma but that will be a seperate issue i'll open :)
