### ISSUE TITLE
install at 40min Reboot entry recovery again

### ISSUE THREAD

**Issue by ladudu** [seven-of-eleven/Lenovo-ThinkPad-L13-Yoga-Hackintosh#3]
hi,i have a Lenovo-ThinkPad-L13(not Yoga),could you give me some help?
intel i31011u

**Comment by seven-of-eleven** [comment]
You'll have to provide details on the issue you're having. If you're getting to the installer and then having issues, then my first question would be did you replace your NVME drive or are you using a Samsung one that the units typically ship with?

**Comment by ladudu** [comment]
i didn't replace any file ,just user your efi.
i use the samsung nvme.

**Comment by seven-of-eleven** [comment]
The Samsung NVME has issues with it. Some have been able to get it working by adding the NVMEfix.kext (I think it is called). For others it never works. Check [here](https://github.com/seven-of-eleven/Lenovo-ThinkPad-L13-Yoga-Hackintosh/issues/2) as sector1952 had the same issue until he changed the NVME drive. Other than that I would recommend you redo the USB mapping and you'll need to generate SMBIOS, Serial #...

**Comment by ladudu** [comment]
![image](https://user-images.githubusercontent.com/26648370/113592982-d17bff00-9670-11eb-9e03-c2abf19e3c39.png)
like this image ,reboot.

**Comment by ladudu** [comment]
I get it, thank you very much for your answer.
so sorry for my bad english. ha ha!

**Comment by seven-of-eleven** [comment]
No problem. If the NVME change doesn't work feel free to reach out again.
