### ISSUE TITLE
Question about firmware

### ISSUE THREAD

**Issue by bennals** [seven-of-eleven/Lenovo-ThinkPad-L13-Yoga-Hackintosh#31]
Hi and thanks for this great repo.

I've just acquired an L13 Yoga and am about to give it a try.  I couldn't see anything in the readme or issues about preferred firmware for the laptop.  It looks like this laptop hasn't been updated since 2020, and on the Lenovo site there is a UEFI BIOS updated from April of this year.

Should I update to this latest one before commencing the installation procedure?

Thanks.

**Comment by Mifaxav** [comment]
You should not have any issues relating to the bios version as far as I remember... 

Update me once you update..!

cheers,
MifaXav (alt of @NotMifa )
