### ISSUE TITLE
Sonoma Installer Reboot Loop

### ISSUE THREAD

**Issue by xtreme1690** [seven-of-eleven/Lenovo-ThinkPad-L13-Yoga-Hackintosh#35]
Hello!

So sadly i've had to start from scratch when it comes to my MacOS install on my L13 Yoga so i figured screw it lets try get Sonoma on this thing. (Solved the previous issue regarding the Airport kexts and kernel panicing)

I've gotten as far as the second stage of the install proess, where the installation reboots from the USB and continues installing from the internal drive. I know another user linked a website in my previous issue regarding the rebooting issue but for the last 3 days that site linked has been coming up as "We are unavailable at this time. Try later." and all i'm finding elsewhere is conflicting info.

So i admit i am looking for a 'quick fix' to get the installation completed. Some say to disable the bluetooth fix kexts, others say just disable the intel airport kexts... but i'd like some solid answers if possible please before i go blindly editing things as this will surely help anyone else with this thinkpad...

Any info would be appreciated, please and thanks!

**Comment by AnomSanjaya** [comment]
Based my experience, im trying to install Sonoma always fail, but success in Venturea. So I install Ventura first and install Sonoma directly from downloaded full installer (not from System Update)

**Comment by xtreme1690** [comment]
Whoops i should've updated this as i ended up getting it to work.

For those who cant access the site mentioned in a previous post, here is what you need to do to get a clean install working
(As well as for those who experience this when doing it from downloading the installer within MacOS)

---

1. Ensure you're running the latest OpenCore and the related kexts are up to date. See [Updating OpenCore and Kexts](https://elitemacx86.com/threads/how-to-update-opencore-bootloader.1371/) for more information.
2. [Mount your ESP](https://elitemacx86.com/threads/how-to-mount-efi-partition-on-macos.932/).
3. Open your config.plist using any [XML editor](https://elitemacx86.com/threads/how-to-edit-config-plist-clover-opencore.933/) from the EFI/OC directory.
4. Set the SecureBootModel to Disabled instead of Default under the Misc>Security section of your config.plist.
5. Save your config.plist.
6. Restart your system for the applied changes to take effect. It is recommended to [reset NVRAM](https://elitemacx86.com/threads/how-to-reset-nvram-clover-opencore.939/) twice at least.

Original location of info: https://elitemacx86.com/threads/how-to-fix-reboot-loop-when-installing-or-updating-to-macos-sonoma-14-4-and-later.1720/
