### ISSUE TITLE
airdrop can not founded any device & wifi isn't work well

### ISSUE THREAD

**Issue by ladudu** [seven-of-eleven/Lenovo-ThinkPad-L13-Yoga-Hackintosh#4]
hi, thank you for your help. I replaced the drive to Intel SSD.it is working very well.
but I have some problems about airdrop.
1. I can't founded  my iPad8 through airdrop. (wifi is working, Bluetooth also working

![截屏2021-04-07 20 32 28](https://user-images.githubusercontent.com/26648370/113859943-6cdfb200-97e0-11eb-9272-8960411d3bcf.png)
2.my notebook link wifi is very slow.(open wifi after 30s(or longer), can't connect)
3.if I didn't shutdown my pc.
   in home, linked a Wifi.(keep power on)
   go to company, linked B wifi.(keep power on )
   come back home,PC auto connected A wifi.
that time I had problems,The Wifi is linking, but network is not work.reboot PC ,network is working.
PC:ThinkPad-L13(not Yoga)

could you give me some suggestions ?

**Comment by seven-of-eleven** [comment]
Assuming you have the latest intel wifi kexts, and your bios is setup correctly everything should work the same with the L13. From what I can tell it has the same WiFi/Bluetooth card as the Yoga I have (some newer Yogas come with the AX201). Check your settings and config.plist to ensure it is setup correctly. Maybe reset you nvram. Otherwise I'd have to take a look at your EFI folder to offer further suggestions.

**Comment by DAlexis74** [comment]
Resetting NVRAM or just hard reset of the notebook might help. The hard reset swich of the notebook is at the middle of the buttom. Also take care as sometimes the system does not boot, as some data is preserved in the NVRAM.

**Comment by seven-of-eleven** [comment]
Following up on the issue with Airdrop.  Seems to be a limitation of the [Intel WiFi kext](https://openintelwireless.github.io/itlwm/FAQ.html#installation):

> Does it support Apple's Continuity Framework (Airdrop, HandOff)
> Only Handoff and Universal Clipboard works with AirportItlwm, other features are not supported.


Handoff and Universal Clipboard are the only supported Continuity features

**Comment by seven-of-eleven** [comment]
I just noticed the released a new version of itlwm for Intel wireless cards. Maybe [give it](https://github.com/OpenIntelWireless/itlwm/releases/tag/v1.3.0) a try.

**Comment by hagenest** [comment]
I can confirm, the new version of itlwm really improves the experience. I get now 110mbit/s instead of 30. It also seems less buggy, but I've only been using it for a day or so.

**Comment by ladudu** [comment]
hi,I updated AirportItlwm_v1.3.0_stable_BigSur.kext,WIFI  can work well.Thanks for everyone.

**Comment by DAlexis74** [comment]
For me it did not work, so I had ro revert to v1.2. Did you upgrade the opencore to 6.8 too?

**Comment by hagenest** [comment]
I stayed on 0.6.7 and it worked fine. Odd, what macOS version are you running?

**Comment by DAlexis74** [comment]
Big Sur 11.2.3

**Comment by ladudu** [comment]
Big Sur 11.2.3,Open Core 0.6.6

**Comment by hagenest** [comment]
@sdombora same for me, odd. Do you get any error messages when booting in verbose mode?

**Comment by DAlexis74** [comment]
> @sdombora same for me, odd. Do you get any error messages when booting in verbose mode?

I did not look at it, I had connection issues - the WPA2 connection was recognized as WPA and I had a warning that the encryption is weak, and the connection was dropped frequently too.

**Comment by seven-of-eleven** [comment]
@DAlexis74 I'm similar to hagenest and sdombora. I haven't experienced any of the issues you've described after updating to v1.3 with OC 0.6.7. I plan to update to MacOS 11.3 and OC 0.6.9 next week when it comes out. I'll update the guide when successful.

**Comment by hieuddo** [comment]
Hi, I have problem with bluetooth. I can turn on bluetooth, connect to my airpods, but cannot connect to any other bluetooth devices (e.g., logitech and xiaomi mouse). Does anyone has the same problem?
