### ISSUE TITLE
OpenCanopy

### ISSUE THREAD

**Issue by sektor1952** [seven-of-eleven/Lenovo-ThinkPad-L13-Yoga-Hackintosh#6]
You said OpenCanopy works, but I can't get the boot chime to work and it seems like the boot menu behaves a little weird with the keyboard.  But everything else seems to be working fine.

**Comment by seven-of-eleven** [comment]
I'm not using OpenCanopy.  I boot directly into MacOS skipping the boot loader selection screen so I never bothered with it or tested it. I know others are using it which is why I reported it as working. Be sure you're using the proper version of OpenCanopy to go with OC 0.6.7.

**Comment by sektor1952** [comment]
I am and I get the boot screen, just n chime and the slight weird issue
with the keyboard.  Also opencore is on 0.68, it would be a nice to have if anyone has any thoughts.

**Comment by seven-of-eleven** [comment]
Not sure if you've resolved this. AFAIK You can't reliably mix different versions of OpenCore. Each version contains changes to config.plist settings/flags and drivers. If you're using opencore 0.6.8 then you should create your config.plist as per the guide.  You can still use my file as a reference. You should also use updated kext files where possible. I'll likely skip 0.6.8 as my laptop is working without issue.  I'll revisit next month when 0.6.9 comes out. Best of luck.

**Comment by sektor1952** [comment]
I didn't resolve it yet and I compared plist files between the 2 and didn't
notice much difference.  I'll go ahead and resolve it, I was wondering if
anyone else would chime in.
