### ISSUE TITLE
Issues during installation

### ISSUE THREAD

**Issue by DAlexis74** [seven-of-eleven/Lenovo-ThinkPad-L13-Yoga-Hackintosh#8]
It was better to use full MacOS installer - easier to build the setup - on macOS Catalina.
After installation I had the following symptoms:
- Could not mount pen drives, even if I could mount them using the https://github.com/hagenest/thinkpad-l13-yoga-hackintosh repository.
- I could not attach external usb memory card readers.
- I could not attach external usb sound cards (headphones, usb sound cards)
- The system was unstable.

After setting the boot parameter "alcid=15" for sound card I could:
- Use all internal sound card functions.
- Add different external USB sound cards (headphones, usb sound cards).
- Mount the pen drives too.
- Attach external monitor using Displayport over USB-C adapter (however it did not detect as a 4K monitor, just a Full HD display). It detected the type and timings this might be a limitation of the Video adapter driver.

So please add the External display support using Displayport adapter through USB-C port too, it works.

**Comment by seven-of-eleven** [comment]
Great to hear that Displayport over USB-C is working, I will add it to the list.  For the USB issues you experienced you may have to create a custom USBMap.kext. The process is outlined on the [Dortania guide here](https://dortania.github.io/OpenCore-Post-Install/usb/). You can replace USBMap.kext with USBInjectAll.kext temporarily (I think you need to change the config.plist - `XhciPortLimit -> True` as well). Thanks for letting me know about the success.  All the best.

**Comment by DAlexis74** [comment]
I had a look on the HDMI too, at the first glance there are anomailes too. Port types were not recognized correctly. There is a possibility to change them,  but I nbeed time to test. So I'm going to give it a try as I have more time.
Thanks for being the pioneer for this great laptop. It runs on 9% of the CPU, while Windows was eating about 50-60%.

**Comment by DAlexis74** [comment]
All HDMI and Display ports are working including 4K mode. An NVRAM reset was needed. 
The sound over HDMI works, but does not have volume control, which is a MacOS limitation.
To make it work just add frambebuffer parameters to the device properties.
I also checked my GPU it has device id: pci ven_8086&dev_ 9b41&SUBSYS_507817AA&REV_02 see the attached images (so it is not natively supported, has to be patched).
I also used the -wegnoegpu in boot-args (I really could not test yet, that it works or not without it).

The code is:

	<key>DeviceProperties</key>
	<dict>
		<key>Add</key>
		<dict>
			<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
			<dict>
				<key>AAPL,slot-name</key>
				<string>Internal@0,2,0</string>
				<key>AAPL,ig-platform-id</key>
				<data>
				AACbPg==
				</data>
				<key>device-id	</key>
				<data>
				mz4AAA==
				</data>
				<key>model</key>
				<string>Intel UHD Graphics 620</string>
				<key>framebuffer-con1-busid</key>
				<data>
				AQAAAA==
				</data>
				<key>framebuffer-con1-enable</key>
				<data>
				AQAAAA==
				</data>
				<key>framebuffer-con1-type</key>
				<data>
				AAgAAA==
				</data>
				<key>framebuffer-patch-enable</key>
				<data>
				AQAAAA==
				</data>
			</dict>
	</dict>



![HDMI_patch](https://user-images.githubusercontent.com/8030353/116974161-f4282480-acbd-11eb-8ee2-9c1832373e08.png)
![VIDEO](https://user-images.githubusercontent.com/8030353/116974970-2ede8c80-acbf-11eb-83a3-c7d378be8840.png)

**Comment by seven-of-eleven** [comment]
@DAlexis74 I used your patches and HDMI works.  I've incorporated them into my EFI with OC 0.6.9. Thanks so much for sharing them have a great weekend.
