### ISSUE TITLE
Possible solution for SD-Card-Reader

### ISSUE THREAD

**Issue by hagenest** [seven-of-eleven/Lenovo-ThinkPad-L13-Yoga-Hackintosh#9]
Hey there,

@DAlexis74 [informed me about a driver for the sd card reader](https://github.com/hagenest/thinkpad-l13-yoga-hackintosh/issues/3). I don't have the time right now to look into it, just wanted to make sure it doesn't get lost.

https://github.com/cholonam/Sinetek-rtsx

**Comment by seven-of-eleven** [comment]
Thanks @hagenest  I'll test it out over the next week.

**Comment by DAlexis74** [comment]
Tested, works. I did not test the speed after adding: rtsx_sleep_wake_delay_ms=1000 parameter.
Read this: https://github.com/cholonam/Sinetek-rtsx/issues/27

The device is not listed in card readers section, but it works. Without the specified parameter it has 9-10MB/s.
